use DB_IPPI
set IDENTITY_INSERT IPPI_Unite ON
insert into IPPI_unite (id_unite, unite) values('1','barquette')
insert into IPPI_unite (id_unite, unite) values('2','Bassine')
insert into IPPI_unite (id_unite, unite) values('3','Boite')
insert into IPPI_unite (id_unite, unite) values('4','bôite')
insert into IPPI_unite (id_unite, unite) values('5','boîte')
insert into IPPI_unite (id_unite, unite) values('6','Boîte de tomate')
insert into IPPI_unite (id_unite, unite) values('7','Boîte de tomate (1 kg)')
insert into IPPI_unite (id_unite, unite) values('8','Boîte de tomate (2 kg)')
insert into IPPI_unite (id_unite, unite) values('9','Boîte de tomate (500 g)')
insert into IPPI_unite (id_unite, unite) values('10','Boîte de tomate/ nescafé')
insert into IPPI_unite (id_unite, unite) values('11','Boîte de tomate/ nescafé (1 kg)')
insert into IPPI_unite (id_unite, unite) values('12','Boîte de tomate/ nescafé (500 g)')
insert into IPPI_unite (id_unite, unite) values('13','Bol')
insert into IPPI_unite (id_unite, unite) values('14','boule')
insert into IPPI_unite (id_unite, unite) values('15','boule ("dankk")')
insert into IPPI_unite (id_unite, unite) values('16','bouteille')
insert into IPPI_unite (id_unite, unite) values('17','bouteille (1 l)')
insert into IPPI_unite (id_unite, unite) values('18','bouteille (1,25 l)')
insert into IPPI_unite (id_unite, unite) values('19','bouteille (1,5 l)')
insert into IPPI_unite (id_unite, unite) values('20','bouteille (33 cl)')
insert into IPPI_unite (id_unite, unite) values('21','bouteille (50 cl)')
insert into IPPI_unite (id_unite, unite) values('22','bouteille (pathial pathial)')
insert into IPPI_unite (id_unite, unite) values('23','bouteille de 1 litre')
insert into IPPI_unite (id_unite, unite) values('24','bouteille de 1,5 litre')
insert into IPPI_unite (id_unite, unite) values('25','bouteille de 10 litres')
insert into IPPI_unite (id_unite, unite) values('26','bouteille de 2 litres')
insert into IPPI_unite (id_unite, unite) values('27','bouteille de 20 litres')
insert into IPPI_unite (id_unite, unite) values('28','bouteille de 25 cl (quart de litre)')
insert into IPPI_unite (id_unite, unite) values('29','bouteille de 5 litres')
insert into IPPI_unite (id_unite, unite) values('30','bouteille de 50 cl')
insert into IPPI_unite (id_unite, unite) values('31','bouteille de 50 cl (demi litre)')
insert into IPPI_unite (id_unite, unite) values('32','bouteille de moins de 50 cl')
insert into IPPI_unite (id_unite, unite) values('33','bouteillle')
insert into IPPI_unite (id_unite, unite) values('34','Calebasse')
insert into IPPI_unite (id_unite, unite) values('35','cannette')
insert into IPPI_unite (id_unite, unite) values('36','carton')
insert into IPPI_unite (id_unite, unite) values('37','carton (brique)')
insert into IPPI_unite (id_unite, unite) values('38','casier')
insert into IPPI_unite (id_unite, unite) values('39','Charrette d''âne')
insert into IPPI_unite (id_unite, unite) values('40','Charrette de boeuf')
insert into IPPI_unite (id_unite, unite) values('41','Charrette de cheval')
insert into IPPI_unite (id_unite, unite) values('42','cornet')
insert into IPPI_unite (id_unite, unite) values('43','couvercle')
insert into IPPI_unite (id_unite, unite) values('44','cuillère à café')
insert into IPPI_unite (id_unite, unite) values('45','cuillère à soupe')
insert into IPPI_unite (id_unite, unite) values('46','cuilllère à café')
insert into IPPI_unite (id_unite, unite) values('47','cuilllère à soupe')
insert into IPPI_unite (id_unite, unite) values('48','cup/gobelet')
insert into IPPI_unite (id_unite, unite) values('49','demi litre')
insert into IPPI_unite (id_unite, unite) values('50','demi tablette')
insert into IPPI_unite (id_unite, unite) values('51','demi-miche')
insert into IPPI_unite (id_unite, unite) values('52','fagot')
insert into IPPI_unite (id_unite, unite) values('53','filet (1 kg)')
insert into IPPI_unite (id_unite, unite) values('54','filet (2,5 kg)')
insert into IPPI_unite (id_unite, unite) values('55','filet (5 kg)')
insert into IPPI_unite (id_unite, unite) values('56','g')
insert into IPPI_unite (id_unite, unite) values('57','Kg')
insert into IPPI_unite (id_unite, unite) values('58','lakhass')
insert into IPPI_unite (id_unite, unite) values('59','Litre')
insert into IPPI_unite (id_unite, unite) values('60','Louche traditionnelle')
insert into IPPI_unite (id_unite, unite) values('61','louche traditionnelle (cokk)')
insert into IPPI_unite (id_unite, unite) values('62','miche')
insert into IPPI_unite (id_unite, unite) values('63','morceau')
insert into IPPI_unite (id_unite, unite) values('64','morceau (100 F)')
insert into IPPI_unite (id_unite, unite) values('65','morceau (25 F)')
insert into IPPI_unite (id_unite, unite) values('66','morceau (50 F)')
insert into IPPI_unite (id_unite, unite) values('67','Moude (2,5 kg)')
insert into IPPI_unite (id_unite, unite) values('68','panier')
insert into IPPI_unite (id_unite, unite) values('69','Panier (Kakut)')
insert into IPPI_unite (id_unite, unite) values('70','Paquet')
insert into IPPI_unite (id_unite, unite) values('71','paquet (1 kg)')
insert into IPPI_unite (id_unite, unite) values('72','paquet (250 g)')
insert into IPPI_unite (id_unite, unite) values('73','paquet (500 g)')
insert into IPPI_unite (id_unite, unite) values('74','Pot')
insert into IPPI_unite (id_unite, unite) values('75','quart de litre')
insert into IPPI_unite (id_unite, unite) values('76','quart de miche')
insert into IPPI_unite (id_unite, unite) values('77','régime')
insert into IPPI_unite (id_unite, unite) values('78','sac')
insert into IPPI_unite (id_unite, unite) values('79','sac (10 kg)')
insert into IPPI_unite (id_unite, unite) values('80','Sac (100 Kg)')
insert into IPPI_unite (id_unite, unite) values('81','Sac (25 Kg)')
insert into IPPI_unite (id_unite, unite) values('82','sac (5 kg)')
insert into IPPI_unite (id_unite, unite) values('83','Sac (50 Kg)')
insert into IPPI_unite (id_unite, unite) values('84','sac ou "saakou" (25 kg)')
insert into IPPI_unite (id_unite, unite) values('85','Sachet')
insert into IPPI_unite (id_unite, unite) values('86','sachet (dents d''ail)')
insert into IPPI_unite (id_unite, unite) values('87','sachet (industrielle)')
insert into IPPI_unite (id_unite, unite) values('88','sachet (mbouss)')
insert into IPPI_unite (id_unite, unite) values('89','sachet 25 cl (walat)')
insert into IPPI_unite (id_unite, unite) values('90','sachet 33 cl')
insert into IPPI_unite (id_unite, unite) values('91','sachet industriel')
insert into IPPI_unite (id_unite, unite) values('92','sachet ou filet (gousse d''ail)')
insert into IPPI_unite (id_unite, unite) values('93','Seau')
insert into IPPI_unite (id_unite, unite) values('94','tablette')
insert into IPPI_unite (id_unite, unite) values('95','tablette (12)')
insert into IPPI_unite (id_unite, unite) values('96','tablette (30)')
insert into IPPI_unite (id_unite, unite) values('97','tablette (6)')
insert into IPPI_unite (id_unite, unite) values('98','tablette (8)')
insert into IPPI_unite (id_unite, unite) values('99','tas')
insert into IPPI_unite (id_unite, unite) values('100','tas (takk)')
insert into IPPI_unite (id_unite, unite) values('101','tiers de miche')
insert into IPPI_unite (id_unite, unite) values('102','tranche')
insert into IPPI_unite (id_unite, unite) values('103','unité')
insert into IPPI_unite (id_unite, unite) values('104','unité (carcasse)')
insert into IPPI_unite (id_unite, unite) values('105','unité (gousse)')
insert into IPPI_unite (id_unite, unite) values('106','unité (pied ou "taate")')
insert into IPPI_unite (id_unite, unite) values('107','unité (sur pied)')
insert into IPPI_unite (id_unite, unite) values('108','unité animale')
insert into IPPI_unite (id_unite, unite) values('109','unité fromage industriel')
insert into IPPI_unite (id_unite, unite) values('110','unité fromage traditionnel')
insert into IPPI_unite (id_unite, unite) values('111','unité volaille')
insert into IPPI_unite (id_unite, unite) values('112','verre')
insert into IPPI_unite (id_unite, unite) values('113','verre à thé')

set IDENTITY_INSERT IPPI_Unite OFF