use DB_IPPI
delete from IPPI_Produit

select * from IPPI_CategorieProduit
set IDENTITY_INSERT IPPI_Produit ON

insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('1','Abats et tripes (foie, rognon, etc.)','2')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('2','Ail','7')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('3','Ananas','5')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('4','Arachide grillée','8')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('5','Arachides décortiquées (fraîches et sèches) ou pilées (noflaye)','8')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('6','Arachides fraîches en coques','8')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('7','Arachides séchées en coques','8')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('8','Attiéke','8')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('9','Aubergine, Courge/Courgette ','7')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('10','Autre Poisson fumé (Con fumé, yaboye ou obo fumé, …)','3')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('11','Avocats','6')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('12','Banane douce','6')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('13','Beignets, galettes','1')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('14','Beurre','4')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('15','Beurre de karité','4')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('16','Bières et vins traditionnels (soumsoum, sung, vin de palme, vin de cajou, etc. ..)','10')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('17','Biscuits','1')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('18','Blé','1')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('19','Canne à sucre','6')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('20','Carotte','6')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('21','Citrons','6')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('22','Concentré de tomate','7')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('23','Concombre','7')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('24','Crabes, crevettes et autres fruits de mer ','3')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('25','Croissants','1')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('26','Dattes','6')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('27','Farine de blé local ou importé','1')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('28','Farine de maïs','1')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('29','Farine de mil','1')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('30','Farines de manioc','8')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('31','Feuilles de baobab / "laalo"','7')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('32','Feuilles de haricot / niébé','7')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('33','Feuilles de manioc, feuilles de taro et, autres feuilles','7')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('34','Feuilles d''oseille (bissap)','7')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('35','Fonio','1')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('36','Fromage','4')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('37','Gari, tapioca','8')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('38','Gâteaux','1')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('39','Gingembre','9')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('40','Gombo frais','7')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('41','Gombo sec','7')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('42','Haricot vert','6')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('43','Huile d''arachide','5')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('44','Huile de coton','5')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('45','Huile de palme rouge','4')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('46','Huile de soja','5')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('47','Igname','8')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('48','Jus de fruits (orange, bissap, etc.)','10')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('49','Lait caillé, yaourt','3')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('50','Lait en poudre','4')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('51','Lait frais','3')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('52','Maïs en épi','1')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('53','Maïs en grain','1')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('54','Mangue','5')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('55','Manioc','8')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('56','Miel','8')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('57','Mil','1')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('58','Niébé/Haricots secs','7')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('59','Noix de coco','6')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('60','Noix de cola','10')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('61','Noix de karité','8')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('62','Œufs ','4')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('63','Oignon frais','7')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('64','Orange ','5')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('65','Pain moderne','1')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('66','Pain traditionnel ','1')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('67','Pastèque, Melon','6')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('68','Patate douce','8')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('69','Pâte d''arachide','8')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('70','Pâtes alimentaires','1')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('71','Petit pois secs','7')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('72','Petits pois ','7')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('73','Piment','8')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('74','Plantain','8')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('75','Poisson frais: thiof/ seudeu (baracouda)','2')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('76','Poisson frais: wass ','3')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('77','Poisson frais: yaboye ou obo (sardinelle)','2')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('78','Poisson fumé: Kethiakh (sardinelle)','3')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('79','Poisson séché','3')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('80','Poisson séché (tambadiang, con, ','3')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('81','Poivron frais','7')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('82','Pomme de terre','8')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('83','Poulet sur pied','2')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('84','Riz importé brisé','1')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('85','Riz importé entier','1')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('86','Riz local brisé','1')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('87','Riz local entier','1')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('88','Salade (laitue, batavia, etc ..)','6')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('89','Sel','8')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('90','Sésame','8')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('91','Sorgho','1')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('92','Soumbala (nététou)','9')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('93','Sucre (poudre ou morceaux)','8')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('94','Taro (diabéré), macabo','8')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('95','Tomate fraîche','7')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('96','Tomate séchée','7')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('97','Viande de bœuf','2')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('98','Viande de chameau','2')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('99','Viande de chèvre','2')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('100','Viande de mouton','2')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('101','Viande de porc','2')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('102','Viande de poulet','2')
insert into IPPI_produit (id_produit, nom_produit, id_categorie) values('103','Vinaigre /moutarde','10')






set IDENTITY_INSERT IPPI_Produit OFF