---set IDENTITY_INSERT IPPI_entreprise on
insert into IPPI_Entreprise (id_Entreprise,ninea, raison_soc, sigle,adresse, telephone,id_produit) values('1','1','ENTREPISE1','ENT1','dakar','77 000 00 01','1')
insert into IPPI_Entreprise (id_Entreprise,ninea, raison_soc, sigle,adresse, telephone,id_produit) values('2','1','ENTREPISE1','ENT1','dakar','77 000 00 01','2')
insert into IPPI_Entreprise (id_Entreprise,ninea, raison_soc, sigle,adresse, telephone,id_produit) values('3','0','ENTREPISE2','ENT2','medina','77 000 00 02','3')
insert into IPPI_Entreprise (id_Entreprise,ninea, raison_soc, sigle,adresse, telephone,id_produit) values('4','0','ENTREPISE2','ENT2','medina','77 000 00 02','4')
insert into IPPI_Entreprise (id_Entreprise,ninea, raison_soc, sigle,adresse, telephone,id_produit) values('5','1','ENTREPISE3','ENT3','colobane','77 000 00 03','5')
insert into IPPI_Entreprise (id_Entreprise,ninea, raison_soc, sigle,adresse, telephone,id_produit) values('6','0','ENTREPISE4','ENT4','pikine','77 000 00 04','10')
insert into IPPI_Entreprise (id_Entreprise,ninea, raison_soc, sigle,adresse, telephone,id_produit) values('7','0','ENTREPISE5','ENT5','fass','77 000 00 05','20')
insert into IPPI_Entreprise (id_Entreprise,ninea, raison_soc, sigle,adresse, telephone,id_produit) values('8','1','ENTREPISE6','ENT6','hlm5','77 000 00 06','15')
insert into IPPI_Entreprise (id_Entreprise,ninea, raison_soc, sigle,adresse, telephone,id_produit) values('9','0','ENTREPISE7','ENT7','medine','77 000 00 07','45')
insert into IPPI_Entreprise (id_Entreprise,ninea, raison_soc, sigle,adresse, telephone,id_produit) values('10','1','ENTREPISE8','ENT8','fan','77 000 00 08','37')
insert into IPPI_Entreprise (id_Entreprise,ninea, raison_soc, sigle,adresse, telephone,id_produit) values('11','1','ENTREPISE9','ENT9','han','77 000 00 09','32')
insert into IPPI_Entreprise (id_Entreprise,ninea, raison_soc, sigle,adresse, telephone,id_produit) values('12','1','ENTREPISE10','ENT10','mermoz','77 000 00 010','11')
insert into IPPI_Entreprise (id_Entreprise,ninea, raison_soc, sigle,adresse, telephone,id_produit) values('13','1','ENTREPISE11','ENT11','ouakam','77 000 00 011','19')
insert into IPPI_Entreprise (id_Entreprise,ninea, raison_soc, sigle,adresse, telephone,id_produit) values('14','1','ENTREPISE12','ENT12','dior','77 000 00 012','49')
insert into IPPI_Entreprise (id_Entreprise,ninea, raison_soc, sigle,adresse, telephone,id_produit) values('15','1','ENTREPISE13','ENT13','yoff','77 000 00 013','43')
insert into IPPI_Entreprise (id_Entreprise,ninea, raison_soc, sigle,adresse, telephone,id_produit) values('16','1','ENTREPISE14','ENT14','liberte6','77 000 00 014','23')
insert into IPPI_Entreprise (id_Entreprise,ninea, raison_soc, sigle,adresse, telephone,id_produit) values('17','1','ENTREPISE15','ENT15','castor','77 000 00 015','27')
insert into IPPI_Entreprise (id_Entreprise,ninea, raison_soc, sigle,adresse, telephone,id_produit) values('18','1','ENTREPISE16','ENT16','bourguiba','77 000 00 016','8')
insert into IPPI_Entreprise (id_Entreprise,ninea, raison_soc, sigle,adresse, telephone,id_produit) values('19','1','ENTREPISE17','ENT17','rufisque','77 000 00 017','9')
insert into IPPI_Entreprise (id_Entreprise,ninea, raison_soc, sigle,adresse, telephone,id_produit) values('20','0','ENTREPISE18','ENT18','diamniadjo','77 000 00 018','12')
insert into IPPI_Entreprise (id_Entreprise,ninea, raison_soc, sigle,adresse, telephone,id_produit) values('21','1','ENTREPISE19','ENT19','dakar','77 000 00 019','39')
insert into IPPI_Entreprise (id_Entreprise,ninea, raison_soc, sigle,adresse, telephone,id_produit) values('22','0','ENTREPISE20','ENT20','grand dakar','77 000 00 020','44')
insert into IPPI_Entreprise (id_Entreprise,ninea, raison_soc, sigle,adresse, telephone,id_produit) values('23','1','ENTREPISE21','ENT21','fass','77 000 00 021','28')
insert into IPPI_Entreprise (id_Entreprise,ninea, raison_soc, sigle,adresse, telephone,id_produit) values('24','1','ENTREPISE22','ENT22','point e','77 000 00 022','17')

---set IDENTITY_INSERT IPPI_entreprise off